export {
  SUPPORTED_CONFIG_VERSION,
  type BaseSpec,
  type PrdSpec,
  type TechnicalDesignSpec,
  type UserStorySpec,
  type TestPlanSpec,
  type AdrSpec,
  type ApiContractSpec,
  type EpicSpec,
  type QuickSpecSpec,
  type ProjectContextSpec,
  type Spec,
  type SpecType,
  type SpecStatus,
  type SpecReference,
  type SpecArtifact,
  type SdxConfig,
  type SpecEntry,
  type PackConfig,
  type PackCompressionConfig,
  type SpecRelationship,
  SPEC_TYPES,
  SPEC_STATUSES,
  SPEC_RELATIONSHIPS,
  DEPENDENCY_RELATIONSHIPS,
} from "./types.js";

export { REQUIRED_SECTIONS } from "./sections.js";
export { validateSpec, validateConfig, type ValidationResult } from "./validator.js";
