import type { Diagnostic } from "@specdx/lint";
import type { DiffResult } from "@specdx/diff";

export function formatComment(
  diagnostics: Diagnostic[],
  specCount: number,
  diffResult: DiffResult | null,
): string {
  const errors = diagnostics.filter((d) => d.severity === "error").length;
  const warnings = diagnostics.filter((d) => d.severity === "warn").length;

  const lines: string[] = [];
  lines.push("## Spec Health Report\n");

  // Lint summary
  const lintIcon = errors > 0 ? "❌" : warnings > 0 ? "⚠️" : "✅";
  lines.push(
    `**Lint:** ${lintIcon} ${specCount} specs checked (${errors} errors, ${warnings} warnings)\n`,
  );

  // Diff section
  if (
    diffResult &&
    (diffResult.diffs.length > 0 || diffResult.added.length > 0 || diffResult.removed.length > 0)
  ) {
    lines.push(
      `**Changes:** ${diffResult.diffs.length} modified, ${diffResult.added.length} added, ${diffResult.removed.length} removed\n`,
    );

    if (diffResult.diffs.length > 0) {
      lines.push("### Changes\n");
      lines.push("| Spec | Sections Modified |");
      lines.push("|------|-------------------|");
      for (const diff of diffResult.diffs) {
        const sections = diff.sections.map((s) => s.heading).join(", ") || "frontmatter only";
        lines.push(`| ${diff.specId} | ${sections} |`);
      }
      lines.push("");
    }

    // Downstream impact
    const allDownstream = diffResult.impact.flatMap((i) => i.downstream);
    if (allDownstream.length > 0) {
      lines.push("### Downstream Impact\n");
      lines.push("| Spec | Staleness | Action Needed |");
      lines.push("|------|-----------|---------------|");
      for (const d of allDownstream) {
        lines.push(`| ${d.specId} | ${d.staleness.toFixed(1)} | ${d.reason} |`);
      }
      lines.push("");
    }
  } else if (diffResult) {
    lines.push("**Changes:** No spec changes detected\n");
  }

  lines.push("---");
  lines.push("*Generated by [specdx](https://github.com/umxr/specdx)*");

  return lines.join("\n");
}
