import * as core from "@actions/core";
import * as github from "@actions/github";
import type { Diagnostic } from "@specdx/lint";
import type { DiffResult } from "@specdx/diff";

/**
 * Marks the comment as ours so a later push updates it instead of stacking a
 * new one. An HTML comment is invisible in the rendered body.
 */
export const COMMENT_MARKER = "<!-- specdx-spec-health -->";

export type CommentOutcome = "posted" | "updated" | "skipped";

export interface PostCommentOptions {
  /** Token with `pull-requests: write`. Empty means commenting is off. */
  token: string;
  /** `ci.post_comment` from the config. */
  enabled: boolean;
  /** Rendered body, without the marker. */
  body: string;
}

/**
 * Post the spec health comment, or explain why it was skipped.
 *
 * Every failure mode is a no-op with a log line and never a job failure: the
 * comment is a convenience, and a spec suite that passed must not go red
 * because the workflow lacked `pull-requests: write`.
 */
export async function postComment({
  token,
  enabled,
  body,
}: PostCommentOptions): Promise<CommentOutcome> {
  if (!enabled) {
    core.info("Spec health comment skipped: post_comment is false in spec.config.yaml.");
    return "skipped";
  }
  if (!token) {
    core.info(
      "Spec health comment skipped: no github-token input. Pass `github-token: ${{ secrets.GITHUB_TOKEN }}` to enable it.",
    );
    return "skipped";
  }

  const pr = github.context.payload.pull_request;
  if (!pr || typeof pr.number !== "number") {
    core.info("Spec health comment skipped: not a pull_request event.");
    return "skipped";
  }
  const issueNumber = pr.number;
  const marked = `${COMMENT_MARKER}\n${body}`;

  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    const existing = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: issueNumber,
      per_page: 100,
    });
    const previous = existing.data.find((c) => c.body?.includes(COMMENT_MARKER));

    if (previous) {
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: previous.id,
        body: marked,
      });
      core.info(`Spec health comment updated (#${previous.id}).`);
      return "updated";
    }

    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body: marked,
    });
    core.info("Spec health comment posted.");
    return "posted";
  } catch (err) {
    core.warning(
      `Spec health comment skipped: ${(err as Error).message}. The workflow needs \`permissions: pull-requests: write\`.`,
    );
    return "skipped";
  }
}

export function formatComment(
  diagnostics: Diagnostic[],
  specCount: number,
  diffResult: DiffResult | null,
): string {
  const errors = diagnostics.filter((d) => d.severity === "error").length;
  const warnings = diagnostics.filter((d) => d.severity === "warn").length;

  const lines: string[] = [];
  lines.push("## Spec Health Report\n");

  // Lint summary — zero specs checked is not a pass (vacuous-pass audit)
  if (specCount === 0) {
    lines.push(
      "**Lint:** ⚠️ no specs were checked — spec paths in `spec.config.yaml` resolved to no files\n",
    );
  } else {
    const lintIcon = errors > 0 ? "❌" : warnings > 0 ? "⚠️" : "✅";
    lines.push(
      `**Lint:** ${lintIcon} ${specCount} specs checked (${errors} errors, ${warnings} warnings)\n`,
    );
  }

  // Diff section
  if (
    diffResult &&
    (diffResult.diffs.length > 0 || diffResult.added.length > 0 || diffResult.removed.length > 0)
  ) {
    lines.push(
      `**Changes:** ${diffResult.diffs.length} modified, ${diffResult.added.length} added, ${diffResult.removed.length} removed\n`,
    );

    if (diffResult.diffs.length > 0) {
      lines.push("### Changes\n");
      lines.push("| Spec | Sections Modified |");
      lines.push("|------|-------------------|");
      for (const diff of diffResult.diffs) {
        const sections = diff.sections.map((s) => s.heading).join(", ") || "frontmatter only";
        lines.push(`| ${diff.specId} | ${sections} |`);
      }
      lines.push("");
    }

    // Downstream impact
    const allDownstream = diffResult.impact.flatMap((i) => i.downstream);
    if (allDownstream.length > 0) {
      lines.push("### Downstream Impact\n");
      lines.push("| Spec | Staleness | Action Needed |");
      lines.push("|------|-----------|---------------|");
      for (const d of allDownstream) {
        lines.push(`| ${d.specId} | ${d.staleness.toFixed(1)} | ${d.reason} |`);
      }
      lines.push("");
    }
  } else if (diffResult) {
    lines.push("**Changes:** No spec changes detected\n");
  }

  lines.push("---");
  lines.push("*Generated by [specdx](https://github.com/umxr/specdx)*");

  return lines.join("\n");
}
