import { formatComment } from "./comment.js";
import type { Diagnostic } from "@specdx/lint";
import type { DiffResult } from "@specdx/diff";

describe("formatComment", () => {
  it("generates clean report with no issues", () => {
    const result = formatComment([], 3, null);
    expect(result).toContain("Spec Health Report");
    expect(result).toContain("✅");
    expect(result).toContain("3 specs checked");
    expect(result).toContain("0 errors");
  });

  it("shows error icon when lint errors exist", () => {
    const diagnostics: Diagnostic[] = [
      { ruleId: "test", severity: "error", message: "bad", filePath: "specs/prd.md" },
    ];
    const result = formatComment(diagnostics, 2, null);
    expect(result).toContain("❌");
    expect(result).toContain("1 errors");
  });

  it("shows warning icon when only warnings", () => {
    const diagnostics: Diagnostic[] = [
      { ruleId: "test", severity: "warn", message: "meh", filePath: "specs/prd.md" },
    ];
    const result = formatComment(diagnostics, 2, null);
    expect(result).toContain("⚠️");
  });

  it("includes changes table when diff has results", () => {
    const diffResult: DiffResult = {
      diffs: [
        {
          specId: "prd",
          filePath: "specs/prd.md",
          frontmatter: [],
          sections: [{ heading: "Goals", type: "modified" }],
          summary: "prd: 1 section changed",
        },
      ],
      added: [],
      removed: [],
      impact: [],
      summary: "1 spec changed",
    };
    const result = formatComment([], 2, diffResult);
    expect(result).toContain("### Changes");
    expect(result).toContain("| prd | Goals |");
  });

  it("includes downstream impact table", () => {
    const diffResult: DiffResult = {
      diffs: [
        { specId: "prd", filePath: "specs/prd.md", frontmatter: [], sections: [], summary: "" },
      ],
      added: [],
      removed: [],
      impact: [
        {
          changedSpec: "prd",
          downstream: [
            {
              specId: "tech",
              filePath: "specs/tech.md",
              distance: 1,
              lastUpdated: null,
              staleness: 0.7,
              reason: "prd changed upstream",
            },
          ],
          totalAffected: 1,
        },
      ],
      summary: "",
    };
    const result = formatComment([], 2, diffResult);
    expect(result).toContain("### Downstream Impact");
    expect(result).toContain("| tech |");
  });

  it("includes footer with link", () => {
    const result = formatComment([], 1, null);
    expect(result).toContain("Generated by [specdx]");
  });
});
